### ISSUE TITLE
error from command quote by keyword

### ISSUE THREAD

**Issue by raccoote** [sukeesh/Jarvis#1037]
When trying to access the quote command in the command prompt, the quote of the day works just fine, but there seems to be a problem with quote by keyword(option 2). I think it happens with any keyword. I'm using a Windows 10 x64 machine.

For example, to recreate this error, open JARVIS in the command prompt, try typing "quote", then "2", then keyword "wisdom". You will get the following text:
```
Traceback (most recent call last):
  File "C:\Users\User\Jarvis\jarviscli\CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "C:\Users\User\Jarvis\jarviscli\plugin.py", line 226, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "C:\Users\User\Jarvis\jarviscli\plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "C:\Users\User\Jarvis\jarviscli\plugins\quote.py", line 24, in __call__
    self.get_keyword_quotes(jarvis, keyword)
  File "C:\Users\User\Jarvis\jarviscli\plugins\quote.py", line 40, in get_keyword_quotes
    quotes = json.loads(res.text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Adrelix** [comment]
Could I be assigned to this issue? I would like to fix it.
