### ISSUE TITLE
error from command 'say'

### ISSUE THREAD

**Issue by raccoote** [sukeesh/Jarvis#1038]
On Windows 10 x64, whenever i run the 'say' command, the following error appears:
```
Traceback (most recent call last):
  File "C:\Users\User\Jarvis\jarviscli\CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "C:\Users\User\Jarvis\jarviscli\plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "C:\Users\User\Jarvis\jarviscli\plugins\voice.py", line 29, in say
    jarvis.say(s)
  File "C:\Users\User\Jarvis\jarviscli\CmdInterpreter.py", line 48, in say
    self._jarvis.speak(text)
  File "C:\Users\User\Jarvis\jarviscli\Jarvis.py", line 118, in speak
    self.speech.text_to_speech(text)
  File "C:\Users\User\Jarvis\jarviscli\utilities\voice.py", line 166, in text_to_speech
    self.engine.setProperty('voices', voices[1].id)  # changing index, changes voices. 1 for female
IndexError: list index out of range
```
The program then crashes and the error persists even when you rerun the program. So Jarvis won't start if you use the 'say' command.
To temporarily solve this issue in your computer you can simply rename 'jarviscli/packages/memory/memory.json' to reset Jarvis memory.
However, we should strive to fix such problems and make our code more accessible, especially for new users.

**Comment by vargemim** [comment]
I get a similar error and behavior when I run the "enable sound" command:

![εικόνα](https://user-images.githubusercontent.com/55913670/223054893-37888631-44f6-42af-bf57-0e02549a3180.png)

**Comment by Yalamarthi97** [comment]
@pnhofmann  I can pick this issue up
My approach.. 
Have a check in place before calling setProperty where if the index is present / len of voices is > index
    If so i can allow the set
    else
       can raise an error or return response that we are not able to do so at the moment due to some error
       
Is it okay?
