### ISSUE TITLE
Error in "Personality Test" plugin

### ISSUE THREAD

**Issue by vargemim** [sukeesh/Jarvis#1052]
When I run the "personality" command for the 2nd, 3rd, etc time, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\mairh\Desktop\Jarvis-master\Jarvis-master\jarviscli\CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "C:\Users\mairh\Desktop\Jarvis-master\Jarvis-master\jarviscli\plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "C:\Users\mairh\Desktop\Jarvis-master\Jarvis-master\jarviscli\plugins\personality.py", line 86, in __call__
    self.get_scores()
  File "C:\Users\mairh\Desktop\Jarvis-master\Jarvis-master\jarviscli\plugins\personality.py", line 58, in get_scores
    self.type.append(personality_type[0])
    ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'append'
```
The quiz only works on the first try. In order to take the quiz again I have to restart Jarvis.
I have the same issue on both Windows 10 and Ubuntu 20.04.

**Comment by raccoote** [comment]
Thank you for reporting this error!

**Comment by pnhofmann** [comment]
#1057
