### ISSUE TITLE
test_timeIn.py failed

### ISSUE THREAD

**Issue by ruzaq** [sukeesh/Jarvis#108]
```
~/b/J/Jarvis $ python -m unittest discover
..Getting Location ... 
.......Song name doesn't exist. (music 'song name') 
...F.Valencia
.E....
======================================================================
ERROR: test_print_say_called_for_all_cmd_help (tests.test_help.HelpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_help.py", line 25, in test_print_say_called_for_all_cmd_help
    mock_print_say.assert_called()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called

======================================================================
FAIL: test_timeIn (tests.test_timeIn.TimeInTest)
test the timeIn.main function against time.ctime
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_timeIn.py", line 36, in test_timeIn
    self.assertEqual(result, time_here)
AssertionError: '6:01:13' != '06:01:13'

----------------------------------------------------------------------
Ran 20 tests in 3.959s

FAILED (failures=1, errors=1)
```

**Comment by StefanosChaliasos** [comment]
@trp07 can you fix it?

**Comment by trp07** [comment]
See PR #115
