### ISSUE TITLE
can't find things in maps

### ISSUE THREAD

**Issue by abrahammurciano** [sukeesh/Jarvis#11]
I get this error when asking for restaurants nearby

Hi, What can I do for you?
restaurants near me
Hold on!, I'll show restaurants near you
Traceback (most recent call last):
  File "/home/abraham/.local/share/jarvis/main.py", line 109, in <module>
    Jarvis(some)
  File "/home/abraham/.local/share/jarvis/main.py", line 41, in Jarvis
    mapps.nearme(data)
  File "/home/abraham/.local/share/jarvis/mapps.py", line 46, in nearme
    url = "https://www.google.co.in/maps/search/{1}/@{2},{3}".format(things, j['latitude'], j['longitude'])
IndexError: tuple index out of range

**Comment by sukeesh** [comment]
This issue has been resolved in latest commit.
