### ISSUE TITLE
can I get some help please?

### ISSUE THREAD

**Issue by CatalinIA7** [sukeesh/Jarvis#1148]
Traceback (most recent call last):
  File "/Users/catalinanton/Jarvis/installer/__main__.py", line 3, in <module>
    from helper import log_init, log_close
  File "/Users/catalinanton/Jarvis/installer/helper.py", line 3, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils'

**Comment by pnhofmann** [comment]
Hmm, okay - distutils appears to be deprecated
https://docs.python.org/3.10/library/distutils.html

So we have to replace this module...

**Comment by pnhofmann** [comment]
Okay, fixed - replaced distutils with shutil.which
