### ISSUE TITLE
python installer not working

### ISSUE THREAD

**Issue by Celiian** [sukeesh/Jarvis#1159]
So basically the problem is that the python installer can't install all dependancies but i don't know why or how to fix it
 : 
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
 

The full error is bellow if needed : 

Jarvis % python3 installer
Logging to /var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/tmp7be1tktk

============== Preparing virtualenv ==============
 
============ Installing requirements =============
 

Installation failed with unexpected error - This should not have happened.
Please check logs at "/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/tmp7be1tktk". If you open a bug report, please include this file.

Jarvis % cat /var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/tmp7be1tktk

============== Preparing virtualenv ==============
________________________________________
Shell: python3 --version
Python 3.12.1

Shell: Exit OK
----------------------------------------

________________________________________
Shell: virtualenv --python=python3 --version
virtualenv 20.25.0 from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/virtualenv/__init__.py

Shell: Exit OK
----------------------------------------

________________________________________
Shell: virtualenv --python=python3 env
created virtual environment CPython3.12.1.final.0-64 in 158ms
  creator CPython3Posix(dest=/Users/celian/Documents/AI/Jarvis/env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/celian/Library/Application Support/virtualenv)
    added seed packages: pip==23.3.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Shell: Exit OK
----------------------------------------

============ Installing requirements =============
________________________________________
Shell: env/bin/pip install -U -r installer/requirements.txt
Ignoring archey4: markers 'sys_platform != "darwin"' don't match your environment
Ignoring pathlib2: markers 'python_version < "3.4"' don't match your environment
Ignoring psutil: markers 'sys_platform == "win32"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring pyreadline: markers 'sys_platform == "win32"' don't match your environment
Ignoring pyttsx3: markers 'sys_platform != "darwin"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring win10toast: markers 'sys_platform == "win32"' don't match your environment
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Collecting beautifulsoup4 (from -r installer/requirements.txt (line 2))
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting climage (from -r installer/requirements.txt (line 3))
  Using cached climage-0.2.0-py3-none-any.whl.metadata (2.7 kB)
Collecting colorama (from -r installer/requirements.txt (line 4))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting distro (from -r installer/requirements.txt (line 5))
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting flake8 (from -r installer/requirements.txt (line 6))
  Using cached flake8-6.1.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting forex-python (from -r installer/requirements.txt (line 7))
  Using cached forex_python-1.8-py3-none-any.whl (8.2 kB)
Collecting geopy (from -r installer/requirements.txt (line 8))
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting gitpython (from -r installer/requirements.txt (line 9))
  Using cached GitPython-3.1.40-py3-none-any.whl.metadata (12 kB)
Collecting googletrans (from -r installer/requirements.txt (line 10))
  Using cached googletrans-3.0.0.tar.gz (17 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting IMDbPY (from -r installer/requirements.txt (line 11))
  Using cached IMDbPY-2022.7.9-py3-none-any.whl (1.2 kB)
Collecting matplotlib (from -r installer/requirements.txt (line 12))
  Using cached matplotlib-3.8.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.8 kB)
Collecting mock (from -r installer/requirements.txt (line 13))
  Using cached mock-5.1.0-py3-none-any.whl.metadata (3.0 kB)
Collecting nltk (from -r installer/requirements.txt (line 14))
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting pdfkit (from -r installer/requirements.txt (line 16))
  Using cached pdfkit-1.0.0-py3-none-any.whl (12 kB)
Collecting pick (from -r installer/requirements.txt (line 17))
  Using cached pick-2.2.0-py3-none-any.whl (4.9 kB)
Collecting pluginmanager (from -r installer/requirements.txt (line 18))
  Using cached pluginmanager-0.4.1-py2.py3-none-any.whl (26 kB)
Collecting pycricbuzz (from -r installer/requirements.txt (line 20))
  Using cached pycricbuzz-2.4-py2.py3-none-any.whl (10 kB)
Collecting pydoc-markdown (from -r installer/requirements.txt (line 21))
  Using cached pydoc_markdown-4.8.2-py3-none-any.whl.metadata (5.9 kB)
Collecting pyjokes (from -r installer/requirements.txt (line 22))
  Using cached pyjokes-0.6.0-py2.py3-none-any.whl (26 kB)
Collecting pync (from -r installer/requirements.txt (line 23))
  Using cached pync-2.0.3.tar.gz (374 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting python-dateutil (from -r installer/requirements.txt (line 26))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytimeparse (from -r installer/requirements.txt (line 27))
  Using cached pytimeparse-1.1.8-py2.py3-none-any.whl (10.0 kB)
Collecting random-word (from -r installer/requirements.txt (line 30))
  Using cached Random_Word-1.0.11-py3-none-any.whl (1.2 MB)
Collecting speedtest-cli (from -r installer/requirements.txt (line 32))
  Using cached speedtest_cli-2.1.3-py2.py3-none-any.whl (23 kB)
Collecting sympy (from -r installer/requirements.txt (line 33))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting tabulate (from -r installer/requirements.txt (line 34))
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting termdown (from -r installer/requirements.txt (line 35))
  Using cached termdown-1.18.0-py3-none-any.whl (21 kB)
Collecting opencv-python-headless (from -r installer/requirements.txt (line 36))
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting whois (from -r installer/requirements.txt (line 37))
  Using cached whois-0.99.3-py3-none-any.whl.metadata (1.6 kB)
Collecting wikipedia (from -r installer/requirements.txt (line 38))
  Using cached wikipedia-1.4.0.tar.gz (27 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting gtts (from -r installer/requirements.txt (line 40))
  Using cached gTTS-2.5.0-py3-none-any.whl.metadata (4.1 kB)
Collecting playsound (from -r installer/requirements.txt (line 41))
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-vlz88auh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-vlz88auh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-vlz88auh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-vlz88auh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: /Users/celian/Documents/AI/Jarvis/env/bin/python -m pip install --upgrade pip

Shell: Exit FAIL Command 'env/bin/pip install -U -r installer/requirements.txt' returned non-zero exit status 1.
----------------------------------------

Installation failed

FATAL!

**Comment by pnhofmann** [comment]
Hey @Lyra126 

basically yes, you are right. Thanks for your response!

This dependencies are getting kind of annoying. The idea was, to only try only use pure-python requirements. But with different systems issues like this seems to keep popping up - like here with a dependency of a dependency.

I think, I'll probably introduce some fail-save mechanism at some point. Like, if one requirement does not install, disable that feature (in this case, the google text to speech), but allow the rest to work probably.

Sorry, I have quite some work to do right now, so this project is a bit of a mess right now. But let's see, I'll try to push some improvements soon.

**Comment by Celiian** [comment]
Hey so i have tried again after updating pip, i also did brew upgrade and my mac is up to date. I tried to install the requirements before starting the installer but whatever i do i have this error now :   
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/celian/Documents/AI/Jarvis/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-zxof1oit/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-zxof1oit/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-zxof1oit/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/85/m6h_lm1575j4q9npm5nsyxsr0000gn/T/pip-build-env-zxof1oit/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Shell: Exit FAIL Command 'env/bin/pip install -U -r installer/requirements.txt' returned non-zero exit status 1.
----------------------------------------

Installation failed

FATAL!
Jarvis % python3 -m pip install setuptools_rust
Requirement already satisfied: setuptools_rust in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.8.1)
Requirement already satisfied: setuptools>=62.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from setuptools_rust) (69.0.3)
Requirement already satisfied: semantic-version<3,>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from setuptools_rust) (2.10.0)


So i may just have to let it go

**Comment by akhil3417** [comment]
facing this same issue

**Comment by KW28** [comment]
I'm also having this issue.

**Comment by Vishnu-ve56** [comment]
I am facing the same issue that was described initially. Can I get a fix for Mac?

[Beginner to open source]
