### ISSUE TITLE
`bored` error

### ISSUE THREAD

**Issue by Kirito139** [sukeesh/Jarvis#1185]
When I ran bored, it spat this out:
```
Traceback (most recent call last):
  File "/Users/lmulder/Jarvis/env/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lmulder/Jarvis/env/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lmulder/Jarvis/env/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/lmulder/Jarvis/env/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lmulder/Jarvis/jarviscli/CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "/Users/lmulder/Jarvis/jarviscli/plugin.py", line 226, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "/Users/lmulder/Jarvis/jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/Users/lmulder/Jarvis/jarviscli/plugins/boredAPI.py", line 20, in __call__
    query = r.json()
            ^^^^^^^^
  File "/Users/lmulder/Jarvis/env/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I'm running Jarvis on a MacBook Air 2020 with M1 chip, macOS Sonoma 14.5, from Terminal.app with zsh as the default shell.

**Comment by lucas-watkins** [comment]
Hey, is it okay if I work on this issue?

**Comment by Kirito139** [comment]
Well if you can work on it despite my having uninstalled Jarvis then go ahead haha. I realized it wasn't really useful for me, what with Siri and all.
