### ISSUE TITLE
On Windows, Jarvis cannot be called from anywhere, only if Jarvis if the current working directory of the terminal

### ISSUE THREAD

**Issue by RyanLatimer** [sukeesh/Jarvis#1225]
# Steps to Produce Issue
1. Clone Jarvis to Github folder in documents,
2. Change the current working directory to that folder to run the installer with Command Prompt
    2.1 The directory must be set to the folder Jarvis in order to run the installer
3. After installing Virtualev and running the installer, the directory remains set to path/to/the/repository
4. The command jarvis is run with the directory set to the repository folder, and a long string of errors emerge.
    4.1 Errors that emerge from running the Jarvis command (Error 1 below)
    4.2 I also tried running the ./jarvis command and received this error (Error 2 Below)
5. The next time I open the terminal Command Prompt, the current working directory is C:/users/my_username
6. The jarvis command and ./jarvis commands result in these errors (Errors 3 and 4 Below)
7. Only when the CD is set to the folder jarvis does jarvis eventually open

# Behavior
- Based on the information provided on this repository, I expected the command jarvis to leda directly to the prompt regardless of the CD. 
- Therefore I find it wrong that jarvis only opens from the folder, and that further still it opens with a long string of errors
- This behavior can be produced reliably every single time I run Jarvis

# Error 1
No module named 'pyautogui'

** (python3.10.exe:3372): WARNING **: 16:15:04.624: Error loading plugin: 'C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\enchant\data\mingw64/lib/enchant-2\enchant_hunspell.dll': The specified module could not be found.

No module named 'PyPDF2'
ERROR:pluginmanager.module_manager:pluginmanager unable to import C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\colorconverter.py
Traceback (most recent call last):
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\module_manager.py", line 71, in load_modules
    module = load_source(plugin_module_name, filepath)
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\PluginManager.py", line 26, in patched_load_source
    return _load_source(*args)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\compat.py", line 63, in load_source
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\colorconverter.py", line 81
    rgb = tuple(map(int, color_value.split(',')))
SyntaxError: expected 'except' or 'finally' block
No module named 'shazamio'
cannot import name 'who' from 'numpy' (C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\numpy\__init__.py)
No module named 'fasttext'
No module named 'akinator'
ERROR:pluginmanager.module_manager:pluginmanager unable to import C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\geolocation.py
Traceback (most recent call last):
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\module_manager.py", line 71, in load_modules
    module = load_source(plugin_module_name, filepath)
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\PluginManager.py", line 26, in patched_load_source
    return _load_source(*args)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\compat.py", line 63, in load_source
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\geolocation.py", line 13
    jarvis.say(f'It\'s located at {api_result_json['city_name']}, {api_result_json['region_name']}, {api_result_json['country_name']}.')
                                                    ^^^^^^^^^
SyntaxError: f-string: unmatched '['
ERROR:pluginmanager.module_manager:pluginmanager unable to import C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\imgur.py
Traceback (most recent call last):
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\module_manager.py", line 71, in load_modules
    module = load_source(plugin_module_name, filepath)
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\PluginManager.py", line 26, in patched_load_source
    return _load_source(*args)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pluginmanager\compat.py", line 63, in load_source
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Family\Documents\Ryan\Jarvis\jarviscli\plugins\imgur.py", line 13, in <module>
    readline = Readline()
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\Family\Documents\Ryan\Jarvis\env\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
Duplicated plugin factor!
# Error 2
'.'  is not recognized as an internal or external command, operable program or batch file

# Error 3
'jarvis' is not recognized as an internal or external command, operable program or batch file

# Error 4
'.'  is not recognized as an internal or external command, operable program or batch file

**Comment by pnhofmann** [comment]
Sorry, won't mess with PATH on windows. Theoretically it would be this:
https://stackoverflow.com/questions/9546324/adding-a-directory-to-the-path-environment-variable-in-windows
Maybe I'll add this to docu
