### ISSUE TITLE
Unable to load Jarvis. On running "jarvis" command.

### ISSUE THREAD

**Issue by ayush-vibrant** [sukeesh/Jarvis#201]
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ayush/Jarvis/jarviscli/__main__.py", line 2, in <module>
    import Jarvis
  File "/home/ayush/Jarvis/jarviscli/Jarvis.py", line 3, in <module>
    from colorama import Fore
ImportError: No module named colorama
![screenshot from 2017-08-13 21-51-20](https://user-images.githubusercontent.com/28810075/29251395-9cba8106-8071-11e7-8cbc-dcbc405b4d08.png)
`

**Comment by jeol16** [comment]
install colorama.
commands (in terminal): 
sudo apt-get install python-colorama

**Comment by umangahuja1** [comment]
I think all modules required should be already installed by running ./setup.sh. Let us know if this isn't the case.

**Comment by tornikegomareli** [comment]
I have same problem, When I'm typing _jarvis_, always have ModuleNotFoundError, when I'm runing ./setup.sh, every module is already installed.

Is this problem for my python versions ? I have 2.7 and also 3.x

**Comment by umangahuja1** [comment]
Well I don't know yet the source of error but just for the purpose of testing I uninstalled colorama and ran jarvis and it show the same error as pointed out and then in Jarvis folder I ran ./setup.sh and then ran jarvis it is working fine.

Still I will try to find the source of error. If anyone gets something feel free to ask issues or chat in gitter.

**Comment by tornikegomareli** [comment]
<img width="615" alt="screen shot 2017-08-14 at 9 40 02 pm" src="https://user-images.githubusercontent.com/24585160/29283792-3a94ccb6-8139-11e7-9fba-747419a71e4a.png">

After lunch ./setup.sh. I'm trying to run Jarvis and this is picture after run it

<img width="610" alt="screen shot 2017-08-14 at 9 40 12 pm" src="https://user-images.githubusercontent.com/24585160/29283845-66f5ff82-8139-11e7-8dba-8e053a49d3f2.png">

Then i install requests, and then it gives me error for bs4, then i install bs4 with pip and it gives me error for imdb.

I know that, those errors are because, I don't have those modules installed, but I think running ./setup.sh must install all of this dependencies.

**Comment by umangahuja1** [comment]
Yup you are right that ./setup.sh should install all of modules required. 
I am not aware about Mac so if someone knows contribute and send a PR or discuss here.

**Comment by tornikegomareli** [comment]
<img width="828" alt="screen shot 2017-08-15 at 12 00 34 pm" src="https://user-images.githubusercontent.com/24585160/29307075-640703b6-81b1-11e7-82cc-4f2d846498d3.png">

In setup.sh there is no OSX condition,is this the reason of the problem ?

**Comment by tornikegomareli** [comment]
When I'm activating virtualenv

`source /env/bin/activate`

Then jarvis command is working

**Comment by appi147** [comment]
@tornikegomareli problem is in setup.sh, virtual environment is set up for installation. Please install dependencies globally by `pip install -r requirements .txt`

**Comment by tornikegomareli** [comment]
@appi147 Yes you are right, thank you for your response.

**Comment by wedjlok** [comment]
I am also getting similar errors. Ran ./setup.sh and it appeared that everything installed fine. However, when I run jarvis from command line in Linux Mint 18.2 (Ubuntu 16.04) I get this error:

`aeryck@andromeda ~ $ jarvis
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aeryck/Jarvis/jarviscli/__main__.py", line 2, in <module>
    import Jarvis
  File "/home/aeryck/Jarvis/jarviscli/Jarvis.py", line 5, in <module>
    from CmdInterpreter import CmdInterpreter
  File "/home/aeryck/Jarvis/jarviscli/CmdInterpreter.py", line 17, in <module>
    from packages.todo import todoHandler
  File "/home/aeryck/Jarvis/jarviscli/packages/todo.py", line 5, in <module>
    from reminder import addReminder, removeReminder
  File "/home/aeryck/Jarvis/jarviscli/packages/reminder.py", line 212, in <module>
    notify2.init("Jarvis")
  File "/usr/lib/python2.7/dist-packages/notify2.py", line 96, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
`

**Comment by appi147** [comment]
@wedjlok This is dbus error, various errors occured related to dbus. This is desktop specific(related to Mint), according to me. Try to install dbus for ypur desktop.

**Comment by wedjlok** [comment]
@appi147 I do already have dbus installed. Perhaps there is a specific dbus package that I need...? I have ubuntu-system-service dbus, dbus ver 1.10.6-1ubuntu3.3, dbusX11, libdbus, as well as some others also.

**Comment by appi147** [comment]
@wedjlok Yeah, there might be a specific dbus package for Mint. Text `org.freedesktop.Notifications` leads us to GNOME, and Unity is based on GNOME. If you could solve this problem this would be a huge help. I'll be looking for the package from my side.

**Comment by appi147** [comment]
@wedjlok Can you try This:
`sudo apt-get install python-dbus-dev python-dbus libdbus-1-dev libdbus-glib-1-dev`

**Comment by jdlowman2** [comment]
I'm also having an issues trying to get setup. After running ./setup.sh, I got the following error: 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bncTkU/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9sijJU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bncTkU/cryptography/

and I also see farther up the error: "Failed building cryptography wheel". Any ideas?

**Comment by appi147** [comment]
@jdlowman2 Cryptography is failing for you. Try installing cryptography first, then setup.sh

**Comment by Mohit17067** [comment]
After running the setup file I got the error that there is no file called requirements.txt so none of the requirements were installed. 
![screenshot from 2017-12-16 00-52-05](https://user-images.githubusercontent.com/32643701/34057022-62e2a56c-e1fb-11e7-9f57-4eb77e69ebef.png)

After that, I ran the same pip command on terminal and there also an error came regarding a requirement. Here is the screenshot for that.
![screenshot from 2017-12-16 00-54-41](https://user-images.githubusercontent.com/32643701/34057145-dd660e0a-e1fb-11e7-8b7f-c62694ad3e29.png)
Although Colorama was installed this time still it shows the same error.
Please explain if I did a mistake somewhere.

**Comment by GrantFleming** [comment]
I had a similar issue on ububtu. Had to manually install loads of modules in the end. Colorama, lotas of the text to speech stuff, beautifulsoup. None of them managed to successfully install on running ./setup.sh

**Comment by GrantFleming** [comment]
Requirements.txt seemed fine. It was where it should be and wasn't corrupt. Managed to automatically ibstall most of the stuff fine but a half dozen of the modules failed for some reason

**Comment by appi147** [comment]
@Mohit17067 @GrantFleming `setup.sh` is written so as to install all the modules in a virtual environment(named env).  It was weird `requirements.txt` being not detected.

**Comment by Mohit17067** [comment]
@GrantFleming @appi147 Did you guys get what was the error while manually running `requirements.txt` (mentioned in the second screenshot)?
I am also confused why requirements.txt was not detected while running setup.sh.

**Comment by Mohit17067** [comment]
Now I ran `setup.sh` and magically everything is installed and `jarvis` command is also working fine.

**Comment by appi147** [comment]
Sure :smile:

**Comment by appi147** [comment]
> Did you guys get what was the error while manually running requirements.txt (mentioned in the second screenshot)?

It was installing in system not in virtualenv

**Comment by Mohit17067** [comment]
Ok. I got it. Thanks

**Comment by cavb1205** [comment]
![captura de pantalla de 2018-03-13 11-14-36](https://user-images.githubusercontent.com/9502237/37347078-cabdc470-26af-11e8-85af-c8d6128c88b1.png)

**Comment by appi147** [comment]
We haven't checked on gnome yet. Seems like an error related to gnome and dbus. Also `sudo jarvis` is not required. Try `jarvis` instead

**Comment by MurphyAdam** [comment]
Hello everyone ^^ So I have spent the last 10 hours just trying to run this Jarvis, I have done everything except the thing that shall make it work, I UPDATED my kernel version, I think. I got all the requirements of the program - Jarvis but still doesn't work. I would really appreciate some help here, thank you so much in advance.

``root@localhost:~# jarvis
/usr/local/bin/jarvis: line 2: /root/Desktop/Jarvis-master/env/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/Desktop/Jarvis-master/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/root/Desktop/Jarvis-master/jarviscli/__main__.py", line 6, in main
    jarvis = Jarvis.Jarvis()
  File "/root/Desktop/Jarvis-master/jarviscli/Jarvis.py", line 48, in __init__
    first_reaction, enable_voice)
  File "/root/Desktop/Jarvis-master/jarviscli/CmdInterpreter.py", line 124, in __init__
    self.speech = voice.Voice()
  File "/root/Desktop/Jarvis-master/jarviscli/utilities/voice.py", line 25, in __init__
    self.create()
  File "/root/Desktop/Jarvis-master/jarviscli/utilities/voice.py", line 33, in create
    self.engine = pyttsx3.init()
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

**Comment by appi147** [comment]
@MurphyAdam  Please install `espeak` and try again

**Comment by MurphyAdam** [comment]
@appi147 I love you man, that really gave me a hard time. Thank you again!!!!

**Comment by kuamit5516** [comment]
jarvis
\/usr/local/bin/jarvis: line 2: /root/Jarvis/env/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/root/Jarvis/jarviscli/__main__.py", line 6, in main
    jarvis = Jarvis.Jarvis()
  File "/root/Jarvis/jarviscli/Jarvis.py", line 48, in __init__
    first_reaction, enable_voice)
  File "/root/Jarvis/jarviscli/CmdInterpreter.py", line 130, in __init__
    self.speech = voice.Voice()
  File "/root/Jarvis/jarviscli/utilities/voice.py", line 25, in __init__
    self.create()
  File "/root/Jarvis/jarviscli/utilities/voice.py", line 33, in create
    self.engine = pyttsx3.init()
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/usr/local/lib/python2.7/dist-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory


@appi147 help me Bhai...


Thanx Advance

**Comment by appi147** [comment]
install `espeak` please?

**Comment by Liu98Fan** [comment]
i have fix this problem,(of course you must make sure that you have installed all the developments )because the command to start jarvis is python ,when your python is not only one version that maybe all developments installed at the python is not the default python version,so you just need to 

cd /usr/local/bin/
sudo nano jarvis 

to modify this jarvis.sh
you will see a command in it like :python ......./../.../jarvis.py 
and you just make sure if the python point the right version
i modified the python with python3 and it works fine

**Comment by hmslima** [comment]
I can't run Jarvis here, in the first time it required _colorama_, I installed it but then it required another package

```
/usr/local/bin/jarvis: linha 2: ~/Jarvis/env/bin/activate: Arquivo ou diretório inexistente
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "~/Jarvis/jarviscli/__main__.py", line 2, in <module>
    import Jarvis
  File "~/Jarvis/jarviscli/Jarvis.py", line 5, in <module>
    from CmdInterpreter import CmdInterpreter
  File "~/Jarvis/jarviscli/CmdInterpreter.py", line 11, in <module>
    from PluginManager import PluginManager
  File "~/Jarvis/jarviscli/PluginManager.py", line 5, in <module>
    import pluginmanager
ImportError: No module named pluginmanager
```

The only _pluginmanager_ I can find in Synaptic is _libzulucryptpluginmanager1.0._0, but I don't think it's the case. I am using Lubuntu 18.04

**Comment by appi147** [comment]
@hmslima Did setup.sh ran successfully?

**Comment by hmslima** [comment]
> Did setup.sh ran successfully?

@appi147 I see now that it is unable to install phantomjs-2.1.1-linux-x86_64.tar.bz2.2

```
phantomjs-2.1.1-linux-x86_64.tar.bz2.3  100%[=========>]  22,33M   464KB/s    em 58s     

2018-07-15 09:58:09 (393 KB/s) - “phantomjs-2.1.1-linux-x86_64.tar.bz2.3” salvo [23415665/23415665]

ln: failed to create a symbolic link '/usr/local/share/phantomjs': file exists
ln: failed to create a symbolic link '/usr/local/bin/phantomjs': file exists
ln: failed to create a symbolic link '/usr/bin/phantomjs': file exists
./setup.sh: line 131: virtualenv: command not found
./setup.sh: line 135: env/bin/activate: linux file or directory nonexistent
./setup.sh: line 136: pip: command not found
./setup.sh: line 137: pip: command not found
```
It's just a mere detail: I've translated the error messages from Portuguese, so some messages may not be exactly equal to an error message of an system in English, but the messages are essentially the same.

**Comment by hmslima** [comment]
I don't know what I have to do to install Jarvis, I even installed this virtualenv through _python3 -m pip install virtualenv_, but I still get that very same error message.

**Comment by redwine629** [comment]
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
 Install virtualenv failed

**Comment by ARUN-S01** [comment]
use pip install JarvisAI==0.0.2

**Comment by pnhofmann** [comment]
> JarvisAI==0.0.2

That is a completely different Jarvis Project ;).
