### ISSUE TITLE
Error on starting jarvis via terminal

### ISSUE THREAD

**Issue by codeShaurya** [sukeesh/Jarvis#302]
While I started Jarvis then these outputs came.

shubham@shaurya:~/Jarvis$ jarvis
Traceback (most recent call last):
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "/home/shubham/Jarvis/env/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shubham/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/home/shubham/Jarvis/jarviscli/__main__.py", line 6, in main
    jarvis = Jarvis.Jarvis()
  File "/home/shubham/Jarvis/jarviscli/Jarvis.py", line 48, in __init__
    first_reaction, enable_voice)
  File "/home/shubham/Jarvis/jarviscli/CmdInterpreter.py", line 123, in __init__
    self.speech = voice.Voice()
  File "/home/shubham/Jarvis/jarviscli/utilities/voice.py", line 25, in __init__
    self.create()
  File "/home/shubham/Jarvis/jarviscli/utilities/voice.py", line 33, in create
    self.engine = pyttsx3.init()
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/home/shubham/Jarvis/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/shubham/Jarvis/env/local/lib/python3.6/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

**Comment by appi147** [comment]
What is the OS, distribution, etc? Try to install `espeak`
