### ISSUE TITLE
Errors on mac

### ISSUE THREAD

**Issue by matthewlewis112** [sukeesh/Jarvis#311]
When running on mac, I get the following errors. How should I debug?
Checking for linting errors
./test.sh: line 5: flake8: command not found
lint errors checked

checking for unit test
EEEE.E.EEEEEEE
======================================================================
ERROR: tests.test_auto.test_music (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_music
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_music.py", line 3, in <module>
    from mock import call, patch
ImportError: No module named mock

======================================================================
ERROR: tests.test_auto.test_tempconv (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_tempconv
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_tempconv.py", line 4, in <module>
    from packages.tempconv import temp_valid_regex, convert_c_to_f, convert_f_to_c
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/packages/tempconv.py", line 3, in <module>
    from utilities.GeneralUtilities import print_say
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/utilities/GeneralUtilities.py", line 5, in <module>
    from colorama import Fore
ImportError: No module named colorama

======================================================================
ERROR: tests.test_auto.test_timeIn (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_timeIn
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_timeIn.py", line 2, in <module>
    from packages import timeIn
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/packages/timeIn.py", line 3, in <module>
    import requests
ImportError: No module named requests

======================================================================
ERROR: tests.test_auto.test_weatherIn (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_weatherIn
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_weatherIn.py", line 2, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: tests.test_auto.test_wiki (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_wiki
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_wiki.py", line 2, in <module>
    import packages.wiki as wiki
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/packages/wiki.py", line 1, in <module>
    import wikipedia
ImportError: No module named wikipedia

======================================================================
ERROR: tests.test_auto.test_lyrics (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_auto.test_lyrics
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_auto/test_lyrics.py", line 2, in <module>
    from packages.lyrics import lyrics
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/packages/lyrics.py", line 2, in <module>
    from utilities.PyLyricsClone import py_lyrics
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/utilities/PyLyricsClone.py", line 9, in <module>
    import requests
ImportError: No module named requests

======================================================================
ERROR: tests.test_manual.test_parser (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_parser
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_parser.py", line 2, in <module>
    from Jarvis import Jarvis
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/Jarvis.py", line 3, in <module>
    from colorama import Fore
ImportError: No module named colorama

======================================================================
ERROR: tests.test_manual.test_evaluator (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_evaluator
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_evaluator.py", line 7, in <module>
    from colorama import Fore
ImportError: No module named colorama

======================================================================
ERROR: tests.test_manual.test_forecast (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_forecast
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_forecast.py", line 3, in <module>
    from mock import patch, call
ImportError: No module named mock

======================================================================
ERROR: tests.test_manual.test_default (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_default
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_default.py", line 2, in <module>
    from Jarvis import Jarvis
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/Jarvis.py", line 3, in <module>
    from colorama import Fore
ImportError: No module named colorama

======================================================================
ERROR: tests.test_manual.test_near_me (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_near_me
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_near_me.py", line 2, in <module>
    from mock import patch
ImportError: No module named mock

======================================================================
ERROR: tests.test_manual.test_help (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_manual.test_help
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/tests/test_manual/test_help.py", line 2, in <module>
    import CmdInterpreter
  File "/Users/matthewlewis/Assistant/Jarvis/jarviscli/CmdInterpreter.py", line 8, in <module>
    from colorama import Fore
ImportError: No module named colorama

----------------------------------------------------------------------
Ran 14 tests in 0.533s

FAILED (errors=12)
unit tests checked

**Comment by appi147** [comment]
looks like modules are not installed. Have you run setup.sh ?

**Comment by matthewlewis112** [comment]
Yes. I also tried using pip install to install the modules individually
