### ISSUE TITLE
Module Plugin manager missing on fresh install

### ISSUE THREAD

**Issue by mrdionjr** [sukeesh/Jarvis#326]
## Current behavior
Throw an exception when I run `$ jarvis`
```
Traceback (most recent call last):
  File "/home/mrdion/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mrdion/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mrdion/projects/jarvis/jarviscli/__main__.py", line 2, in <module>
    import Jarvis
  File "/home/mrdion/projects/jarvis/jarviscli/Jarvis.py", line 5, in <module>
    from CmdInterpreter import CmdInterpreter
  File "/home/mrdion/projects/jarvis/jarviscli/CmdInterpreter.py", line 11, in <module>
    from PluginManager import PluginManager
  File "/home/mrdion/projects/jarvis/jarviscli/PluginManager.py", line 5, in <module>
    import pluginmanager
ModuleNotFoundError: No module named 'pluginmanager'
```

## Expected behavior
Run the command without error

## Steps to reproduce
1- git clone the repo
2- Run `$ ./setup.py`
3- Run `$ jarvis`

## Current environment
- Manjaro Linux
- Anaconda 3 (python 3.6)

## Additional comments
The installation run without error. All the dependencies are correctly installed.

**Comment by mrdionjr** [comment]
Installing the package manually solved the problem. I run the setup on another machine with a vanilla python3.6 installation. However, the same error kept appearing so I activated the virtualenv and installed the module. It solved the problem.
Note that this solution does not work with Anaconda.
