### ISSUE TITLE
Remove dbus and other non python dependencies

### ISSUE THREAD

**Issue by StefanosChaliasos** [sukeesh/Jarvis#336]
We should consider to make jarvis more universal and more maintainable. I propose to remove dependencies like dbus and refactor the code base to work with only python packages. All the active members of this project are welcome to participate in this discussion. @appi147 @pnhofmann @sukeesh @kaynaat007 @jpigree @gucharbon

**Comment by StefanosChaliasos** [comment]
In the first place we could remove those features and then find replacements to implement them again. The installation process should be universal on any os with just a pip install. I will create a new branch for this issue do you want to work on it @pnhofmann ?

**Comment by appi147** [comment]
@StefanosChaliasos Instead of removing we could add wrappers like IS_DEBIAN. e.g. IS_MACOS implemented by @danielcorin  [here](https://github.com/sukeesh/Jarvis/blob/4bf7aa3e2e7e6bac3ae1001aa7305c0458b0804f/jarviscli/CmdInterpreter.py#L15).

In long term, IMO e should remove all package manager dependencies

**Comment by pnhofmann** [comment]
Thanks for collaborator invitation ;) !
I'll see what I can do.

**Comment by hugolesta** [comment]
Hello there,

After install Jarvis the installation returns the following error:

```
    checking for Python include path... -I/usr/include/python2.7
    checking for Python library path... -L/usr/lib -lpython2.7
    checking for Python site-packages path... /usr/lib/python2.7/dist-packages
    checking python extra libraries... -lpthread -ldl  -lutil -lm
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-build-Go1dr4/dbus-python/build/temp.linux-x86_64-2.7':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================

    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Go1dr4/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Go1dr4/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-Go1dr4/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python', '--prefix=/tmp/pip-build-Go1dr4/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Go1dr4/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ju0tsM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Go1dr4/dbus-python/
```
I let you know my screenfetch details


![image](https://user-images.githubusercontent.com/6575715/45628845-59766b00-ba6b-11e8-8359-9f64ddbaaa5a.png)


I have some experiene developing on personal projects. Could you please tell me if I can colaborate with this project?

Regards!

**Comment by appi147** [comment]
@hugolesta Try devel versions of python, see if it works.

**Comment by pnhofmann** [comment]
Update:

Made first progress: I managed to rewrite phantomjs in hackathon with requests only. Should also run faster :). Pushed to no_natives_python_only.

Unfortunately I noticed, facebook and twitter also need chromium.
- Twitter: Noticed there is an api. Will try to rewrite this command.
- Facebook: This command just opens facebook and performance login? And just if you are using chromium? Could make this command optionally (active only if chromium exists) but would propose to remove with no replacement
- Reminder/Todo: Currently I think it would be best to replace dbus-notification with native command "notify-send". If notify-send is not installed, we could open small python-window as fallback. Could implement something...
- screenfetch: Definitly make "systeminfo" with screenfetch optionally - could probably also try to get and print some system information with python only. Shouldn't be a problem.
- Text To speech: I'll soon add some lines to use jarvis without audio if no tts is not installed. Don't think there is a python-only tts engine with no dependencies.
- ffmpeg: didn't took a closer look

**Comment by pnhofmann** [comment]
Twitter in fact has an api for tweets - and also python-library:
https://github.com/bear/python-twitter/blob/master/examples/tweet.py

Unfortunately this needs an API key.
https://developer.twitter.com/en/apply-for-access

Yeah - please help. No experience with that ;).
Especially since this is an Open Source application - I can't just register there and "Open Source" the key, can I?

**Comment by StefanosChaliasos** [comment]
You shouldn't. So remove that feature from your version and open an issue.

**Comment by appi147** [comment]
Since python 2 is coming to an end in [Jan1 2020](https://pythonclock.org/). Should we stop maintaining both python2 and python3 and focus on python3?

**Comment by pnhofmann** [comment]
Would definitely have no problem with no python2 support! Is there actually anyone running a system without python 3 installed?
But also think maintaining python2 wouldn't be too much work - so I don't really care too much.
