### ISSUE TITLE
Unable to run Jarvis

### ISSUE THREAD

**Issue by beatboxerish** [sukeesh/Jarvis#337]
I have an Ubuntu 18.04 with Anaconda installed(My default python interpreter is the anaconda python). After installing, typing 'jarvis' in the command line gives me the following error:

/usr/local/bin/jarvis: line 2: /home/ish/python_repos/Jarvis/env/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "/home/ish/anaconda3/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ish/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ish/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ish/python_repos/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/home/ish/python_repos/Jarvis/jarviscli/__main__.py", line 6, in main
    jarvis = Jarvis.Jarvis()
  File "/home/ish/python_repos/Jarvis/jarviscli/Jarvis.py", line 49, in __init__
    directories, first_reaction, enable_voice)
  File "/home/ish/python_repos/Jarvis/jarviscli/CmdInterpreter.py", line 150, in __init__
    self.speech = voice.Voice()
  File "/home/ish/python_repos/Jarvis/jarviscli/utilities/voice.py", line 25, in __init__
    self.create()
  File "/home/ish/python_repos/Jarvis/jarviscli/utilities/voice.py", line 33, in create
    self.engine = pyttsx3.init()
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/home/ish/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/drivers/espeak.py", line 5, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/ish/anaconda3/lib/python3.6/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/home/ish/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/ish/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

**Comment by pnhofmann** [comment]
Hi!
> OSError: libespeak.so.1: cannot open shared object file: No such file or directory
That's interesting - please verify, that libespeak1 is installed.
If yes, check if /usr/lib/x86_64-linux-gnu/libespeak.so.1 exists.

Additionally I'm currently working on a patch that disables text to speech support if this error occurs - but lets everything else work (first version 59f5ba6ad5b28e1839929cb9abf84854d9b795f9 on python_dependencies_only branch).

> /usr/local/bin/jarvis: line 2: /home/ish/python_repos/Jarvis/env/bin/activate: No such file or directory
Oh - I see. Suppose that's related to Anaconda.

We install all python requirements to a virtualenv in Jarvis/env. Guess virtualenv is not installed on your system (?) - but looks like the virtualenv was not created and Jarvis dependencies were installed to your Anaconda directory.

Guess, that won't stop Jarvis from running - but it's a second issue I'll try to address as soon as possible.

**Comment by beatboxerish** [comment]
So i installed libespeak1 and virtualenv and it works now :) . But when i use calculate 5 + 4, it says couldn't identify command.

**Comment by appi147** [comment]
#201
