### ISSUE TITLE
"remind" broken?

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#339]
```
~> What can i do for you?
remind add 14:25 buy tomatoes
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/tmp/Jarvis/jarviscli/__main__.py", line 7, in main
    jarvis.executor()
  File "jarviscli/Jarvis.py", line 173, in executor
    self.cmdloop(self.first_reaction_text)
  File "/usr/lib64/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "jarviscli/CmdInterpreter.py", line 603, in do_remind
    reminder_handler(data)
  File "jarviscli/utilities/GeneralUtilities.py", line 62, in wrapped
    func(*args, **kwargs)
  File "jarviscli/packages/reminder.py", line 190, in reminder_handler
    globals()[action](data)
KeyError: 'handlerAdd'
```

Apparently this is just a simple typo - looks like during Reflactoring "handlerAdd" was renamed "handler_add" - without renaming in `` addAction("handlerAdd", ["add", "new", "create"], minArgs=1)``.

The interesting part: This file was last modified about a year ago (19. Oct 2017). So I guess, probably nobody is using this feature? 

Did implement something to send notifications without python-dbus for #336 - but I noticed other problems:

* remind (and also todo) should use jarviscli.packages.memory.memory instead writing their own files
* Don't really like the way the command is processed (``A match is determined by similarity between request and the available reminder names.`` Processing like that should be implemented on a application-level - and not in one command. There are interesting libraries (https://www.nltk.org/, https://rustyonrampage.github.io/text-mining/2017/11/28/spelling-correction-with-python-and-nltk.html). In fact honestly I already planted to take a closer look at those - but guess that's another story ;).
* Want to write something like "remind me in 10 minutes to take pizza out of oven"

=> Anyone would mind if I completely re-implement this module (and probably also parts of todo)? Any suggestions / thoughts?

**Comment by StefanosChaliasos** [comment]
Go for it @pnhofmann !
