### ISSUE TITLE
"Check time in" not working

### ISSUE THREAD

**Issue by pnhofmann** [sukeesh/Jarvis#342]
```
~> Hi, what can I do for you?
check time in Greenwich, UK
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/phil/projects/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/home/phil/projects/Jarvis/jarviscli/__main__.py", line 7, in main
    jarvis.executor()
  File "/home/phil/projects/Jarvis/jarviscli/Jarvis.py", line 173, in executor
    self.cmdloop(self.first_reaction_text)
  File "/usr/lib64/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/phil/projects/Jarvis/jarviscli/CmdInterpreter.py", line 299, in do_check
    timeIn.main(self, s)
  File "/home/phil/projects/Jarvis/jarviscli/packages/timeIn.py", line 12, in main
    loc = getLocation(s)
  File "/home/phil/projects/Jarvis/jarviscli/packages/timeIn.py", line 34, in getLocation
    lat = j['results'][0]['geometry']['location']['lat']    # Latitude
IndexError: list index out of range
```
Guess the API changed...

**Comment by appi147** [comment]
google maps api is giving this error
```
{
   "error_message" : "You have exceeded your rate-limit for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}

```
thus list index out of range error

**Comment by appi147** [comment]
Working correctly with key
```
17:47 $ python timeIn.py 
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "Greenwich",
               "short_name" : "Greenwich",
               "types" : [ "neighborhood", "political" ]
            },
            {
               "long_name" : "London",
               "short_name" : "London",
               "types" : [ "postal_town" ]
            },
            {
               "long_name" : "Greater London",
               "short_name" : "Greater London",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "England",
               "short_name" : "England",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "United Kingdom",
               "short_name" : "GB",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "SE10 9NN",
               "short_name" : "SE10 9NN",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "Greenwich, London SE10 9NN, UK",
         "geometry" : {
            "location" : {
               "lat" : 51.48257659999999,
               "lng" : -0.0076589
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : 51.4895247,
                  "lng" : 0.0083485
               },
               "southwest" : {
                  "lat" : 51.4756274,
                  "lng" : -0.0236663
               }
            }
         },
         "place_id" : "ChIJ83WZp86p2EcRbMrkYqGncBQ",
         "types" : [ "neighborhood", "political" ]
      }
   ],
   "status" : "OK"
}

51.48257659999999 -0.0076589

```

**Comment by appi147** [comment]
Register here for timein key : https://console.developers.google.com/apis/credentials?project=_
