### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signature'

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#350]
```
09:11 $ python2 jarviscli/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/appi/Public/github/Jarvis/jarviscli/__main__.py", line 11, in <module>
    main()
  File "/home/appi/Public/github/Jarvis/jarviscli/__main__.py", line 6, in main
    jarvis = Jarvis.Jarvis()
  File "jarviscli/Jarvis.py", line 51, in __init__
    directories, first_reaction, enable_voice)
  File "jarviscli/CmdInterpreter.py", line 158, in __init__
    self._activate_plugins()
  File "jarviscli/CmdInterpreter.py", line 162, in _activate_plugins
    for (plugin_name, plugin) in self._plugin_manager.get_all().items():
  File "jarviscli/PluginManager.py", line 148, in get_all
    self._load()
  File "jarviscli/PluginManager.py", line 51, in _load
    if self._plugin_validate(plugin):
  File "jarviscli/PluginManager.py", line 63, in _plugin_validate
    if not self._plugin_has_method(plugin, "run", 2):
  File "jarviscli/PluginManager.py", line 89, in _plugin_has_method
    params = inspect.signature(getattr(plugin, method)).parameters
AttributeError: 'module' object has no attribute 'signature'
```

`inspect.signature() was added in Python 3`
Line [here](https://github.com/sukeesh/Jarvis/blob/c37296e1a90e5a44cd6320c372c9cb84b2697799/jarviscli/PluginManager.py#L89)

**Comment by appi147** [comment]
@pnhofmann
