### ISSUE TITLE
systeminfo plugin doesnt work on macos

### ISSUE THREAD

**Issue by bsushmith** [sukeesh/Jarvis#387]
Running the command systeminfo on mac gives the below error - 

`Traceback (most recent call last):
  File "/Users/Sushmith/GitHub/Jarvis/jarviscli/CmdInterpreter.py", line 143, in try_do
    do(s)
  File "/Users/Sushmith/GitHub/Jarvis/jarviscli/plugin.py", line 116, in __run_method
    run_method(jarvis, s)
  File "/Users/Sushmith/GitHub/Jarvis/jarviscli/plugins/systemOptions.py", line 36, in systeminfo__PY3
    from archey import archey
  File "/Users/Sushmith/GitHub/Jarvis/env/lib/python3.6/site-packages/archey/archey.py", line 519, in <module>
    '-o', 'comm', '--no-headers'], universal_newlines=True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ps', '-u501', '-o', 'comm', '--no-headers']' returned non-zero exit status 1.`

I tried to resolve it by removing the --no-headers by doing "comm=", but there are more issues as the plugin is trying  to find /proc/cpuinfo file and it goes down a rabbithole.

It seems more like the systeminfo plugin should be disabled for mac

**Comment by bsushmith** [comment]
@pnhofmann I'm trying the understand the project and In the PR [#389](https://github.com/sukeesh/Jarvis/pull/389), shouldnt the updated snippet be

```python
@plugin(python=PYTHON3, plattform=MACOS, native="screenfetch")
def systeminfo__PY3_MAC(jarvis, s):
    """Display system information with distribution logo"""
    os.system("screenfetch")```

**Comment by pnhofmann** [comment]
Definitely! Shouldn't program 'on the hop'.
