### ISSUE TITLE
clear plugin fails due to arguments issue

### ISSUE THREAD

**Issue by bsushmith** [sukeesh/Jarvis#392]
clear expects 0 arguments as per definition but two are sent as per the design. 

~> What can i do for you?
clear
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/Users/Sushmith/GitHub/Jarvis/jarviscli/CmdInterpreter.py", line 143, in try_do
    do(s)
  File "/Users/Sushmith/GitHub/Jarvis/jarviscli/plugin.py", line 116, in __run_method
    run_method(jarvis, s)
TypeError: clear() takes 0 positional arguments but 2 were given

**Comment by pnhofmann** [comment]
#391
