### ISSUE TITLE
Curvesketch have an error...

### ISSUE THREAD

**Issue by Zml99** [sukeesh/Jarvis#425]
I tried to open the curvesketch and it give this error:
```
Traceback (most recent call last):
  File "/home/nicolai/Jarvis/jarviscli/CmdInterpreter.py", line 143, in try_do
    do(s)
  File "/home/nicolai/Jarvis/jarviscli/plugin.py", line 116, in __run_method
    run_method(jarvis, s)
  File "/home/nicolai/Jarvis/jarviscli/plugins/evaluator.py", line 266, in curvesketch
    term = solve_y(term)
  File "/home/nicolai/Jarvis/jarviscli/plugins/evaluator.py", line 224, in solve_y
    return solve_y("({}) -y".format(s))
  File "/home/nicolai/Jarvis/jarviscli/plugins/evaluator.py", line 216, in solve_y
    results = sympy.solve(s, y)
  File "/home/nicolai/Jarvis/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1162, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/nicolai/Jarvis/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1498, in _solve
    f_num, sol = solve_linear(f, symbols=symbols)
  File "/home/nicolai/Jarvis/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 2073, in solve_linear
    n, d = eq.as_numer_denom()
  File "/home/nicolai/Jarvis/env/lib/python3.6/site-packages/sympy/core/add.py", line 446, in as_numer_denom
    content, expr = self.primitive()
  File "/home/nicolai/Jarvis/env/lib/python3.6/site-packages/sympy/core/add.py", line 916, in primitive
    c, m = a.as_coeff_Mul()
AttributeError: 'Tuple' object has no attribute 'as_coeff_Mul'

```

**Comment by pnhofmann** [comment]
Thanks for reporting this one! Curvesketch needs an argument (e.g. curve sketch x**2+10x-5).

I'll add a meaningful message later.

**Comment by Zml99** [comment]
Ohh....I didn't knew that. I will try that way next time.
