### ISSUE TITLE
ValueError when entering bad character in 'cricket' plugin 

### ISSUE THREAD

**Issue by Farlgerann** [sukeesh/Jarvis#435]
Hi,
While trying some commands in Jarvis, I tried to enter another type of value in "cricket" input field. It seems like types errors are not handled by the module, and it returns something like this :

```Traceback (most recent call last):
  File "/tmp/Jarvis/jarviscli/CmdInterpreter.py", line 155, in try_do
    do(self, s)
  File "/tmp/Jarvis/jarviscli/plugin.py", line 219, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "/tmp/Jarvis/jarviscli/plugin.py", line 201, in run
    self._backend[0](jarvis.get_api(), s)
  File "/tmp/Jarvis/jarviscli/plugins/cricket.py", line 19, in __call__
    self.score(jarvis)
  File "/tmp/Jarvis/jarviscli/plugins/cricket.py", line 144, in score
    choice = int(input(Fore.RED + '\nEnter choice (number): ' + Fore.RESET))
ValueError: invalid literal for int() with base 10: 'l'
```
I think I can fix it, if it's a relevant issue; but I am beginner and I'm not sure my fix is ... clean ?
Nevertheless, it passed the tests successfully.

**Comment by pnhofmann** [comment]
Hi!

Thanks for reporting this issue.

> but I am beginner and I'm not sure my fix is ... clean ?

No problem at all! We are happy about any contribution. Just send a PR.

**Comment by pnhofmann** [comment]
#436
