### ISSUE TITLE
Movie: two methods are broken

### ISSUE THREAD

**Issue by appi147** [sukeesh/Jarvis#441]
Movie search and movie info is broken because of incorrect method defined in line 220.
Variable `move_attributes` is iterated however it is undefined in line 228 of movie.py.
Error log:
```
movie info interstellar

Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "jarviscli/CmdInterpreter.py", line 151, in try_do
    do(self, s)
  File "jarviscli/plugin.py", line 209, in run
    self.get_plugins(command).run(jarvis, new_s)
  File "jarviscli/plugin.py", line 219, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "jarviscli/plugin.py", line 201, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 150, in movie_info
    get_movie_info(jarvis, data)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 228, in get_movie_info
    for attribute in movie_attributes:
NameError: name 'movie_attributes' is not defined

```

```
movie search interstellar

ID   Movie title
1    Interstellar (2014)
2    Interstelar 2: Operation Terra 2040 (2016)
3    Interstellar Civil War: Shadows of the Empire (2017)
4    Interstellar Wars (2016)
5    Interstelar (2014)

Please enter ID to know more(q - quit):
1

Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "jarviscli/CmdInterpreter.py", line 151, in try_do
    do(self, s)
  File "jarviscli/plugin.py", line 209, in run
    self.get_plugins(command).run(jarvis, new_s)
  File "jarviscli/plugin.py", line 219, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "jarviscli/plugin.py", line 201, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 208, in movie_search
    get_movie_info(jarvis, data)
  File "/home/appi/Public/github/Jarvis/jarviscli/plugins/movie.py", line 228, in get_movie_info
    for attribute in movie_attributes:
NameError: name 'movie_attributes' is not defined


```

**Comment by qwireq** [comment]
Can you assign this issue to me?

**Comment by appi147** [comment]
Sure go ahead

**Comment by qwireq** [comment]
Could you check my pull request, please? #447
