### ISSUE TITLE
Plot issue

### ISSUE THREAD

**Issue by usman-kakakhel** [sukeesh/Jarvis#457]
Hey guys,
This error occured when I tried to use plot. I dont know whether it is a problem with plot or my PC but anyways, here is the error.

Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "/home/usman/Downloads/Jarvis-master/jarviscli/CmdInterpreter.py", line 151, in try_do
    do(self, s)
  File "/home/usman/Downloads/Jarvis-master/jarviscli/plugin.py", line 201, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/usman/Downloads/Jarvis-master/jarviscli/plugins/evaluator.py", line 117, in plot
    calc(jarvis, s, calculator=solve_y, formatter=_plot, do_evalf=False)
  File "/home/usman/Downloads/Jarvis-master/jarviscli/plugins/evaluator.py", line 230, in calc
    result = calculator(s)
  File "/home/usman/Downloads/Jarvis-master/jarviscli/plugins/evaluator.py", line 224, in solve_y
    return solve_y("({}) -y".format(s))
  File "/home/usman/Downloads/Jarvis-master/jarviscli/plugins/evaluator.py", line 216, in solve_y
    results = sympy.solve(s, y)
  File "/home/usman/Downloads/Jarvis-master/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1162, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/usman/Downloads/Jarvis-master/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1498, in _solve
    f_num, sol = solve_linear(f, symbols=symbols)
  File "/home/usman/Downloads/Jarvis-master/env/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 2073, in solve_linear
    n, d = eq.as_numer_denom()
  File "/home/usman/Downloads/Jarvis-master/env/lib/python3.6/site-packages/sympy/core/add.py", line 446, in as_numer_denom
    content, expr = self.primitive()
  File "/home/usman/Downloads/Jarvis-master/env/lib/python3.6/site-packages/sympy/core/add.py", line 916, in primitive
    c, m = a.as_coeff_Mul()
AttributeError: 'Tuple' object has no attribute 'as_coeff_Mul'

**Comment by pnhofmann** [comment]
Hi,

how embarrassing! Especially since we had a similar issue before. You need to add the function you want to plot immediately after plot - e.g. 'plot x**2' - but of course you could not know this ;).

Thanks for reporting this one! I've just uploaded a 2 line patch for a clean error message.

**Comment by usman-kakakhel** [comment]
@pnhofmann thankyou for responding, I have been trying to learn how to use jarvis but it has been hard uptill now. As I do not know how to use certain commands. If there was a how to file available that would be appreciated. 
Thankyou.

**Comment by pnhofmann** [comment]
There is the help command - which will print all available commands or help for one command (mostly with examples). E.g.:

```
~> Hi, what can I do for you?
help plot
Plot graph

Subcommands:
--Examples:
    plot x**2
    plot y=x(x+1)(x-1)
```

Certainly - this help system could be improved. But isn't a help command more practical than a "how to"-file?

**Comment by usman-kakakhel** [comment]
Indeed it is more practical, thanks for all the help!
