### ISSUE TITLE
import colorama error

### ISSUE THREAD

**Issue by paulrm** [sukeesh/Jarvis#5]
Even I installed the colorama package
 
```
# pip list --format=legacy | grep colorama 
colorama (0.3.7)`
```
I got a weird import error
```
# python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import os, sys, json, todo, newws, pyowm, mapps, picshow, requests, evaluator, audioHandler
  File "/root/src/Jarvis/todo.py", line 2, in <module>
    from colorama import init
ImportError: No module named colorama
```

**Comment by dviraj00** [comment]
What is the solution for this? i also have the same exact case
