### ISSUE TITLE
Create a plugin to Jarvis

### ISSUE THREAD

**Issue by marcjal** [sukeesh/Jarvis#592]
Hi 👋! I have some problems trying to add a new plugin to Jarvis so I created my plugin.py file and imported the module `from plugin import plugin, alias` some interesting is this message ```from plugin import plugin, alias
ModuleNotFoundError: No module named 'plugin' ``` and I have problems to teste Jarvis from the repo I don’t know how to install it... I used Jarvis from the release, download the .zip and install it.

Thanks community 😃

**Comment by pnhofmann** [comment]
Hi!

> and I have problems to teste Jarvis from the repo I don’t know how to install it... I used Jarvis from the release, download the .zip and install it.

This zip?
https://github.com/sukeesh/Jarvis/releases

Yes, that's an older version of Jarvis using old installer. For new version - like documented in README.md - use:

```In order to start Jarvis just clone this repository repository and run python installer.```

> I have some problems trying to add a new plugin to Jarvis so I created my plugin.py file 

So to eliminate all misunderstanding:

* Your plugin is either located in custom or in jarviscli/plugins
* You don't call your plugin directly - but start Jarvis with 'jarvis' just like you would start jarvis
* You receive output similar to :

```
ERROR:pluginmanager.module_manager:pluginmanager unable to import /home/phil/git/Jarvis/custom/test.py
Traceback (most recent call last):
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/pluginmanager/module_manager.py", line 71, in load_modules
    module = load_source(plugin_module_name, filepath)
  File "/home/phil/git/Jarvis/env/lib/python3.6/site-packages/pluginmanager/compat.py", line 63, in load_source
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/phil/git/Jarvis/custom/test.py", line 1, in <module>
    import abcd
ModuleNotFoundError: No module named 'abcd'
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
106 plugins loaded 6 plugins disabled. More information: status

~> Hi, what can I do for you?
```

But afterwards Jarvis is working - you can call commands, just not the one you added?
