### ISSUE TITLE
Spinner error in akinator plugin

### ISSUE THREAD

**Issue by akshgpt7** [sukeesh/Jarvis#624]
The akinator plugin raises a series of errors when you press "g" to start, and Jarvis exits.

```
Traceback (most recent call last):
  File "/home/aksh/Jarvis/jarviscli/CmdInterpreter.py", line 223, in try_do
    do(self, s)
  File "/home/aksh/Jarvis/jarviscli/plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/aksh/Jarvis/jarviscli/plugins/akinator.py", line 25, in akinator_main
    main_game(jarvis)
  File "/home/aksh/Jarvis/jarviscli/plugins/akinator.py", line 49, in main_game
    q = aki.start_game()
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/akinator/akinator.py", line 125, in start_game
    self._get_session_info()
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/akinator/akinator.py", line 85, in _get_session_info
    r = requests.get("https://en.akinator.com/game")
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/aksh/Jarvis/env/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='en.akinator.com', port=443): Max retries exceeded with url: /game (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aksh/Jarvis/jarviscli/__main__.py", line 22, in <module>
    main()
  File "/home/aksh/Jarvis/jarviscli/__main__.py", line 17, in main
    jarvis.executor(command)
  File "/home/aksh/Jarvis/jarviscli/Jarvis.py", line 184, in executor
    self.cmdloop(self.first_reaction_text)
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/aksh/Jarvis/jarviscli/CmdInterpreter.py", line 227, in try_do
    if self.is_spinner_running():
AttributeError: 'Jarvis' object has no attribute 'is_spinner_running'
```

**Comment by pnhofmann** [comment]
Thanks for reporting this bug!

Lesson for me learned: Don't trust code analyze tools blindly... Just because a tool says: ```s = p.sub(r'\1*\2', s)``` should be ```s = p.sub(r'\\1*\\2', s)``` doesn't mean the tools is correct. In this case ``\1`` is correct ;).

Is a bit ugly, because underlying library does require to type: ``10*x`` and not ``10x``. So I'm using regex to make ``10x`` -> ``10*x``. But should work now!

#626
