### ISSUE TITLE
SyntaxError given when run with curve sketch example

### ISSUE THREAD

**Issue by owainrutherford** [sukeesh/Jarvis#625]
```
Missing parameter: function (e.g. call 'curve sketch y=x**2+10x-5')
~> What can I do for you?
curve sketch y=x**2+10x-5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sympy/core/sympify.py", line 384, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/local/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 966, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/local/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 879, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Symbol ('y' )-(Symbol ('x' )**Integer (2 )+\Integer (1 )*\Integer (2 )-Integer (5 ))
                                                                                       ^
SyntaxError: unexpected character after line continuation character

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/jarviscli/CmdInterpreter.py", line 223, in try_do
    do(self, s)
  File "/app/jarviscli/plugin.py", line 217, in run
    self.get_plugins(command).run(jarvis, new_s)
  File "/app/jarviscli/plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
  File "/app/jarviscli/plugins/evaluator.py", line 284, in curvesketch
    term = solve_y(term)
  File "/app/jarviscli/plugins/evaluator.py", line 229, in solve_y
    results = sympy.solve(s, y)
  File "/usr/local/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 922, in solve
    f, symbols = (_sympified_list(w) for w in [f, symbols])
  File "/usr/local/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 922, in <genexpr>
    f, symbols = (_sympified_list(w) for w in [f, symbols])
  File "/usr/local/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 913, in _sympified_list
    return list(map(sympify, w if iterable(w) else [w]))
  File "/usr/local/lib/python3.6/site-packages/sympy/core/sympify.py", line 386, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse 'y - (x**2+\\1*\\2-5)'' failed, because of exception being raised:
SyntaxError: unexpected character after line continuation character (<string>, line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/jarviscli/__main__.py", line 22, in <module>
    main()
  File "/app/jarviscli/__main__.py", line 17, in main
    jarvis.executor(command)
  File "/app/jarviscli/Jarvis.py", line 184, in executor
    self.cmdloop(self.first_reaction_text)
  File "/usr/local/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/app/jarviscli/CmdInterpreter.py", line 227, in try_do
    if self.is_spinner_running():
AttributeError: 'Jarvis' object has no attribute 'is_spinner_running'
Makefile:7: recipe for target 'run_docker' failed
make: *** [run_docker] Error 1
```

Don't get the error if you type:
```curve sketch y==x**2+10*x-5```

**Comment by pnhofmann** [comment]
Thanks for reporting this bug!

Lesson for me learned: Don't trust code analyze tools blindly... Just because a tool says: ```s = p.sub(r'\1*\2', s)``` should be ```s = p.sub(r'\\1*\\2', s)``` doesn't mean the tools is correct. In this case ``\1`` is correct ;).

Is a bit ugly, because underlying library does require to type: ``10*x`` and not ``10x``. So I'm using regex to make ``10x`` -> ``10*x``. But should work now!

#626
