### ISSUE TITLE
[BUG] AttributeError if evaluator.limit is given an empty parameter

### ISSUE THREAD

**Issue by aazuspan** [sukeesh/Jarvis#649]
The issue: evaluator.limit throws an AttributeError if it isn't passed a parameter when it is called. Confirmed on Windows, but looking at the source, it should happen on any platform. 

To reproduce the bug: use the command `limit` with no parameter.

Let me know if you want me to tackle this.

```
Traceback (most recent call last):
  File "C:\Users\az\opensource\Jarvis\jarviscli\CmdInterpreter.py", line 223, in try_do
    do(self, s)
  File "C:\Users\az\opensource\Jarvis\jarviscli\plugin.py", line 209, in run
    self._backend[0](jarvis.get_api(), s)
  File "C:\Users\az\opensource\Jarvis\jarviscli\plugins\evaluator.py", line 166, in limit
    term = solve_y(term)
  File "C:\Users\az\opensource\Jarvis\jarviscli\plugins\evaluator.py", line 237, in solve_y
    return solve_y("({}) -y".format(s))
  File "C:\Users\az\opensource\Jarvis\jarviscli\plugins\evaluator.py", line 229, in solve_y
    results = sympy.solve(s, y)
  File "C:\Users\az\opensource\Jarvis\env\lib\site-packages\sympy\solvers\solvers.py", line 1174, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "C:\Users\az\opensource\Jarvis\env\lib\site-packages\sympy\solvers\solvers.py", line 1511, in _solve
    f_num, sol = solve_linear(f, symbols=symbols)
  File "C:\Users\az\opensource\Jarvis\env\lib\site-packages\sympy\solvers\solvers.py", line 2086, in solve_linear
    n, d = eq.as_numer_denom()
  File "C:\Users\az\opensource\Jarvis\env\lib\site-packages\sympy\core\add.py", line 466, in as_numer_denom
    content, expr = self.primitive()
  File "C:\Users\az\opensource\Jarvis\env\lib\site-packages\sympy\core\add.py", line 948, in primitive
    c, m = a.as_coeff_Mul()
AttributeError: 'Tuple' object has no attribute 'as_coeff_Mul'
```

**Comment by pnhofmann** [comment]
#660
