### ISSUE TITLE
 Произошла непредвиденная ошибка. Пожалуйста, откройте вопрос на GitHub! вот ошибка:

### ISSUE THREAD

**Issue by TS-Pra** [sukeesh/Jarvis#657]
Traceback (most recent call last):
  File "/home/ts/Документы/Новый/Jarvis/installer/__main__.py", line 16, in <module>
    import steps.d_optional
  File "installer/steps/d_optional.py", line 32, in <module>
    if check_optional_requirement(requirement):
  File "installer/steps/d_optional.py", line 15, in check_optional_requirement
    if shell(CMD).success():
  File "installer/helper.py", line 152, in shell
    log(cli_output)
  File "installer/helper.py", line 53, in log
    debug_log.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 632-640: ordinal not in range(128)

**Comment by pnhofmann** [comment]
Sorry, English only...

Don't fully understand this error, but since this error happens just during logging, i did push #660 - which just catches the error from your Traceback.
Probably related to python 2, which handles string / unicode differently?

If error persists or similar error shows up, please re-open this issue.
