### ISSUE TITLE
Stuck on Download additional data directory (wordnet)

### ISSUE THREAD

**Issue by ashvinstech** [sukeesh/Jarvis#682]
Stuck on Download additional data directory (wordnet) for like an hours, tried everything, opened again, reinstalled. but same problem

**Comment by pnhofmann** [comment]
Hi!
that's strange...

What's the content of ``jarviscli/data/nltk``? How big is this folder?
What's the output of (ran from Jarvis directory):

```
env/bin/python -m nltk.downloader -d jarviscli/data/nltk wordnet
env/bin/python -m nltk.downloader -d jarviscli/data/nltk punkt
```

or (windows):

```
env\Scripts\python.exe -m nltk.downloader -d jarviscli/data/nltk wordnet
env\Scripts\python.exe -m nltk.downloader -d jarviscli/data/nltk punkt
```

**Comment by ashvinstech** [comment]
```
env/bin/python -m nltk.downloader -d jarviscli/data/nltk wordnet
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
Error installing package. Retry? [n/y/e]
y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ashvinbhagat/development/Jarvis-master/env/lib/python3.8/site-packages/nltk/downloader.py", line 2533, in <module>
    rv = downloader.download(
  File "/Users/ashvinbhagat/development/Jarvis-master/env/lib/python3.8/site-packages/nltk/downloader.py", line 793, in download
    msg.package.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

```
env/bin/python -m nltk.downloader -d jarviscli/data/nltk punkt
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
Error installing package. Retry? [n/y/e]
y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ashvinbhagat/development/Jarvis-master/env/lib/python3.8/site-packages/nltk/downloader.py", line 2533, in <module>
    rv = downloader.download(
  File "/Users/ashvinbhagat/development/Jarvis-master/env/lib/python3.8/site-packages/nltk/downloader.py", line 793, in download
    msg.package.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by JettChenT** [comment]
I got the same results.

**Comment by pnhofmann** [comment]
``CERTIFICATE_VERIFY_FAILED``

Doesn't look like Jarvis-issue. Quick search stackoverflow:

https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python

Might be caused by e.g. running software like Fiddler (or probably virus scanner or other stuff sniffing https traffic).

Other answer suggest, setting env variable ``REQUESTS_CA_BUNDLE``. But Sorry, don't really know. ``certifi`` should actually provide working CA certificates.
