### ISSUE TITLE
Akinator AtributeError

### ISSUE THREAD

**Issue by valuechip** [sukeesh/Jarvis#763]
Was playing with the Akinator module. No issues until it attempted to guess a personality which it seemed to have been missing a "name" attribute.

OS: Ubuntu 20.04.1 LTS

>Does your character wear shades?
no
Does your character have curly hair?
yes
Some error occurred, please open an issue on github!
Here is error:

>Traceback (most recent call last):
  File "/home/valuechip/Documents/Projects/gits/Jarvis/jarviscli/CmdInterpreter.py", line 287, in try_do
    do(self, s)
  File "/home/valuechip/Documents/Projects/gits/Jarvis/jarviscli/plugin.py", line 226, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "/home/valuechip/Documents/Projects/gits/Jarvis/jarviscli/plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "/home/valuechip/Documents/Projects/gits/Jarvis/jarviscli/plugins/akinator.py", line 26, in akinator_main
    main_game(jarvis)
  File "/home/valuechip/Documents/Projects/gits/Jarvis/jarviscli/plugins/akinator.py", line 88, in main_game
    correct = jarvis.input(f"It's {aki.name} ({aki.description})! Was I correct?\n\t")
AttributeError: 'Akinator' object has no attribute 'name'

**Comment by pnhofmann** [comment]
Hi!
Thanks for reporting this issue! Looks like Akinator api changed upstream.
Upstream example replaced ``{aki.name}`` with ``{aki.first_guess['name']}`` and ``{aki.description}`` with ``{aki.first_guess['description']}``.
