### ISSUE TITLE
Jarvis fail on help command

### ISSUE THREAD

**Issue by Bersam** [sukeesh/Jarvis#766]
Hey,
So I was trying this tool and I notice `help` command will break the setup... I have ubuntu 18.04 and python3.6.9, and I'm running `./jarvis`.

```
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
163 plugins loaded 6 plugins disabled. More information: status

~> Hi, what can I do for you?

I could not identify your command...
~> What can I do for you?
elp
I could not identify your command...
~> What can I do for you?
fasdfdas
I could not identify your command...
~> What can I do for you?
help

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bersamk/workspace/Jarvis/jarviscli/__main__.py", line 22, in <module>
    main()
  File "/home/bersamk/workspace/Jarvis/jarviscli/__main__.py", line 17, in main
    jarvis.executor(command)
  File "/home/bersamk/workspace/Jarvis/jarviscli/Jarvis.py", line 189, in executor
    self.cmdloop()
  File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/bersamk/workspace/Jarvis/jarviscli/CmdInterpreter.py", line 463, in do_help
    print_say("", self)
  File "/home/bersamk/workspace/Jarvis/jarviscli/utilities/GeneralUtilities.py", line 28, in print_say
    self.speech.text_to_speech(text)
  File "/home/bersamk/workspace/Jarvis/jarviscli/utilities/voice.py", line 66, in text_to_speech
    tts = gTTS(speech, lang="en")
  File "/home/bersamk/workspace/Jarvis/env/lib/python3.6/site-packages/gtts/tts.py", line 120, in __init__
    assert text, 'No text to speak'
AssertionError: No text to speak
```

**Comment by pnhofmann** [comment]
Hi and Thanks!
took a closer look - it's a small mess ;). ``help`` still uses the ``utilities/GeneralUtilities.py:print_say`` method - which is legacy. Think we should remove this method completely; will work on this soon.

**Comment by Bersam** [comment]
Hi @pnhofmann, I spend a bit time and prepared a small fix for this, I assumed the right method, in this case, is the JarvisAPI.say, please let me know if it's not the case :)
