### ISSUE TITLE
errors running jarvis.bar

### ISSUE THREAD

**Issue by youdass101** [sukeesh/Jarvis#826]
(env) PS E:\Coding\lab\Jarvis> .\jarvis.bat
No module named 'fasttext'
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
159 plugins loaded 26 plugins disabled. More information: status

Traceback (most recent call last):
  File "c:\users\hamze\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hamze\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Coding\lab\Jarvis\jarviscli\__main__.py", line 22, in <module>
    main()
  File "E:\Coding\lab\Jarvis\jarviscli\__main__.py", line 15, in main
    jarvis = Jarvis.Jarvis()
  File "E:\Coding\lab\Jarvis\jarviscli\Jarvis.py", line 61, in __init__
    CmdInterpreter.__init__(self, first_reaction_text, prompt,
  File "E:\Coding\lab\Jarvis\jarviscli\CmdInterpreter.py", line 365, in __init__
    self._api.say(self.first_reaction_text)
  File "E:\Coding\lab\Jarvis\jarviscli\CmdInterpreter.py", line 48, in say
    self._jarvis.speak(text)
  File "E:\Coding\lab\Jarvis\jarviscli\Jarvis.py", line 118, in speak
    self.speech.text_to_speech(text)
  File "E:\Coding\lab\Jarvis\jarviscli\utilities\voice.py", line 69, in text_to_speech
    playback.play(audio)
  File "E:\Coding\lab\Jarvis\env\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "E:\Coding\lab\Jarvis\env\lib\site-packages\pydub\playback.py", line 15, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "E:\Coding\lab\Jarvis\env\lib\site-packages\pydub\audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "E:\Coding\lab\Jarvis\env\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\myuser\\AppData\\Local\\Temp\\tmpit9sw4dw.wav'

**Comment by pnhofmann** [comment]
> Permission denied: 'C:\Users\myuser\AppData\Local\Temp\tmpit9sw4dw.wav'

Hmm - 'myuser' is your user account?

Can you check permission of this folder / check if it exists? You should definitely have write-permission on your whole Home - especially (I guess that's your) %TMP%. Looks like an issue with your Windows-installation.
