### ISSUE TITLE
Error with 'help' command.

### ISSUE THREAD

**Issue by jronzo99** [sukeesh/Jarvis#881]
Hi, 
I'm getting and error that only occurs when I type the 'help' command yet it seems to be related to gTTS.
I ran 
```
pip install gTTS
```
and it installs without issues.
This is the output that I get:
```(env) Johns-MacBook-Pro-2:Jarvis john$ jarvis
Jarvis' sound is by default disabled.
In order to let Jarvis talk out loud type: enable sound
Type 'help' for a list of available actions.
171 plugins loaded 21 plugins disabled. More information: status

~> Hi, what can I do for you?
help

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/john/Jarvis/jarviscli/__main__.py", line 22, in <module>
    main()
  File "/Users/john/Jarvis/jarviscli/__main__.py", line 17, in main
    jarvis.executor(command)
  File "/Users/john/Jarvis/jarviscli/Jarvis.py", line 189, in executor
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/john/Jarvis/jarviscli/CmdInterpreter.py", line 467, in do_help
    self.say("")
  File "/Users/john/Jarvis/jarviscli/CmdInterpreter.py", line 48, in say
    self._jarvis.speak(text)
  File "/Users/john/Jarvis/jarviscli/Jarvis.py", line 118, in speak
    self.speech.text_to_speech(text)
  File "/Users/john/Jarvis/jarviscli/utilities/voice.py", line 66, in text_to_speech
    tts = gTTS(speech, lang="en")
  File "/Users/john/Jarvis/env/lib/python3.9/site-packages/gtts/tts.py", line 131, in __init__
    assert text, 'No text to speak'
AssertionError: No text to speak
```

**Comment by pnhofmann** [comment]
Thanks for reporting this issue! 

Interesting, Jarvis apparently does talk out load - even though sound shouldn't be enabled. I'll look into this!
Second issue, of course text_to_speech should not do anything if text is empty. This should be an easy fix.

**Comment by KitaPDev** [comment]
@pnhofmann Hi, is this issue still relevant? I would like the chance to work on it as a part of an assignment for my Software Development class.
