### ISSUE TITLE
Error with equations

### ISSUE THREAD

**Issue by siddharth123-tech** [sukeesh/Jarvis#905]
Traceback (most recent call last):
  File "C:\Users\siddh\OneDrive\Documents\GitHub\Jarvis\jarviscli\CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "C:\Users\siddh\OneDrive\Documents\GitHub\Jarvis\jarviscli\plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "C:\Users\siddh\OneDrive\Documents\GitHub\Jarvis\jarviscli\plugins\evaluator.py", line 86, in equations
    calc(
  File "C:\Users\siddh\OneDrive\Documents\GitHub\Jarvis\jarviscli\plugins\evaluator.py", line 264, in calc
    result = result.evalf()
AttributeError: 'list' object has no attribute 'evalf'

![image](https://user-images.githubusercontent.com/82219365/137783751-c531a640-c884-46c8-b15c-19e85eea3f58.png)

**Comment by pnhofmann** [comment]
Thanks for reporting this issue

**Comment by viniciusdepadua** [comment]
Hi, is this issue still open? could I help? I'm new on contributing to open source projects. thx

**Comment by pnhofmann** [comment]
#908
