### ISSUE TITLE
syntax error in instalation

### ISSUE THREAD

**Issue by MedAly666** [sukeesh/Jarvis#948]
what should I do for this :

```
Traceback (most recent call last):
  File "/home/medaly/Jarvis/installer/__main__.py", line 17, in <module>
    import steps.e_launcher
  File "installer/steps/e_launcher.py", line 54
    print(f"NO .{user_shell}rc found!")
                                     ^
SyntaxError: invalid syntax
```

**Comment by pnhofmann** [comment]
Thanks.
Older Python installation doesn't support the f"..." syntax. Switched to "".format().
