### ISSUE TITLE
Akinator Error

### ISSUE THREAD

**Issue by MATHEROS5DEV** [sukeesh/Jarvis#998]
Some error occurred, please open an issue on github!
Here is error:

Traceback (most recent call last):
  File "E:\JARVIS\jarviscli\plugins\akinator.py", line 75, in main_game
    q = aki.answer(a)
TypeError: argument 'answer': 'str' object cannot be converted to 'Answer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\JARVIS\jarviscli\CmdInterpreter.py", line 286, in try_do
    do(self, s)
  File "E:\JARVIS\jarviscli\plugin.py", line 226, in _plugin_run_with_network_error
    run_func(jarvis, s)
  File "E:\JARVIS\jarviscli\plugin.py", line 208, in run
    self._backend[0](jarvis.get_api(), s)
  File "E:\JARVIS\jarviscli\plugins\akinator.py", line 26, in akinator_main
    main_game(jarvis)
  File "E:\JARVIS\jarviscli\plugins\akinator.py", line 76, in main_game
    except akinator.InvalidAnswerError:
AttributeError: module 'akinator' has no attribute 'InvalidAnswerError'

**Comment by lstgl** [comment]
Hey, I have also had this error
I found a way to fix it and made a PR

**Comment by pnhofmann** [comment]
Merged #1006
